### ISSUE TITLE
Build broken?

### ISSUE THREAD

**Issue by jorgeimperial** [posulliv/libcassandra#7]
I am trying to build the libraries on Centos5.4.   

Configuration summary for libcassandra version 0.1
- Installation prefix:       /usr/local
- System type:               pc-linux-gnu
- Host CPU:                  i686
- C Compiler:                gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-46)
- C++ Compiler:              g++ (GCC) 4.1.2 20080704 (Red Hat 4.1.2-46)
- Assertions enabled:        yes
- Debug enabled:             no
- Warnings as failure:       yes
- C++ cstdint location:      <stdint.h>
- C++ hash_map location:     <ext/hash_map>
- C++ hash namespace:        __gnu_cxx
- C++ shared_ptr namespace:  

When trying to make, I get the error

In file included from /usr/local/include/thrift/Thrift.h:40,
from /usr/local/include/thrift/transport/TTransport.h:23,  
from /usr/local/include/thrift/protocol/TProtocol.h:23,
from /usr/local/include/thrift/TProcessor.h:24,
from libgenthrift/Cassandra.h:9,
from libgenthrift/Cassandra.cpp:6:
/usr/local/include/thrift/TLogging.h:69:33: error: anonymous variadic macros were introduced in C99
/usr/local/include/thrift/TLogging.h:91:35: error: anonymous variadic macros were introduced in C99
/usr/local/include/thrift/TLogging.h:102:40: error: anonymous variadic macros were introduced in C99
/usr/local/include/thrift/TLogging.h:113:31: error: anonymous variadic macros were introduced in C99
/usr/local/include/thrift/TLogging.h:130:37: error: anonymous variadic macros were introduced in C99
/usr/local/include/thrift/TLogging.h:148:36: error: anonymous variadic macros were introduced in C99

I am using thrift-0.3.0

**Comment by themanatuf** [comment]
I suspect it has something to do with your compiler, but it's just a guess. I'm using gcc version 4.4.3 (Ubuntu 4.4.3-4ubuntu5) and don't have any problems building. You did execute:
    ./config/autogen.sh
first, right?

**Comment by jorgeimperial** [comment]
Yes, I ran the autogen script first, and my environment is different: Centos 5.5, gcc 4.1.2.

But if also failed to build in OSX 10.6...

**Comment by minaguib** [comment]
I've used this to work-around the issue till I investigate further:

./configure CXXFLAGS="-I/opt/local/include -Wno-variadic-macros"

**Comment by jorgeimperial** [comment]
Ok, I have tried it with thrift 0.2.0 and it works.  I guess the problem is with 0.3.0 and 0.4.0 (also tested as not working...)

Thanks!

**Comment by minaguib** [comment]
The current posulliv/libcassandra/master branch is paired with thrift 0.2

My branch at minaguib/libcassandra/master has been updated to thrift 0.4

Note that in both branches, cassandra 0.6 is a requirement. I'm planning to support cassandra 0.7 sometime later.

**Comment by jorgeimperial** [comment]
All working now (thrift .4.0)  Thanks a lot!

**Comment by jorgeimperial** [comment]
I guess I should close.
